spring:
  application:
    name: AtlProject
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8096
  mail:
    host: smtp.gmail.com
    port: 587
    username: shirinovabanu20@gmail.com
    password: Banu2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true